import type { Metadata } from 'next';
import './globals.css';
import { PageLayout } from '@/shared/layouts';
import { quicksand } from '@/shared/fonts';

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang='en'>
      <body className={quicksand.className}>
        <PageLayout>{children}</PageLayout>
      </body>
    </html>
  );
}
